backer:
  image: dockerizedrupal/backer:2.0.0
  hostname: backer
  environment:
    SERVER_NAME: localhost
    TIMEZONE: Etc/UTC
    MYSQL_HOST:
    MYSQL_PORT: 3306
    MYSQL_USERNAME: container
    MYSQL_PASSWORD: container
    CRON_EXPRESSION: 0 0 * * *
    S3: Off
    S3_ACCESS_KEY_ID:
    S3_SECRET_ACCESS_KEY:
    S3_REGION:
    S3_BUCKET:
    S3_MAX_RETRIES: 10
    S3_RETRY_WAITSEC: 30
    S3_KEEP: 30
    ARCHIVE: Off
    ARCHIVE_ADD:
    MAIL: Off
    MAIL_FROM:
